export const GET_CARDS_START = 'GET_CARDS_START';
export const GET_CARDS_ERROR = 'GET_CARDS_ERROR';
export const GET_CARDS_SUCCESS = 'GET_CARDS_SUCCESS';


export const ADD_NEW_CARD_TO_SELECTED = 'ADD_NEW_CARD_TO_SELECTED';

export const CHANGE_TYPE = 'CHANGE_TYPE';
export const REMOVE_CARD = 'REMOVE_CARD';

export const SEARCH_HERO = 'SEARCH_HERO'